# ai_messenger Configuration Example
#
# This file demonstrates all available configuration options
# with their default values and explanations.

[server]
# Base path prefix for all routes (default: "")
# Examples: "", "api", etc.
# base_path = "api"

# Server bind address (default: "127.0.0.1")
# Use "0.0.0.0" to bind to all interfaces
# host = "127.0.0.1"

# Server port (default: 8080)
# port = 3000

[storage]
# Custom data directory for persistent storage (optional)
# If not set, uses platform-specific directory:
# - macOS: ~/Library/Application Support/com.christiangrete.ai_messenger
# - Linux: ~/.local/share/com.christiangrete.ai_messenger
# - Windows: %APPDATA%\com.christiangrete.ai_messenger
#
# Supports home directory expansion:
# - Use ~ at the beginning: "~/my_app_data"
# - Use $HOME anywhere: "$HOME/.local/my_app_data"
# data_dir = "~/.ai_messenger/data"

# Custom cache directory for temporary files (optional)
# If not set, uses platform-specific cache directory:
# - macOS: ~/Library/Caches/com.christiangrete.ai_messenger
# - Linux: ~/.cache/com.christiangrete.ai_messenger
# - Windows: %LOCALAPPDATA%\com.christiangrete.ai_messenger
#
# Supports home directory expansion:
# - Use ~ at the beginning: "~/my_app_cache"
# - Use $HOME anywhere: "$HOME/.cache/my_app"
# cache_dir = "~/.ai_messenger/cache"

# Service adapters configuration
[adapters.llm]
# Provider identifier and version
provider = "ollama"
version = "0.0.1-alpha"

# Provider-specific configuration (passed through to adapter)
[adapters.llm.config]
# Ollama server configuration
base_url = "http://localhost:11434"
keep_alive = "5m"

# Default model and parameters - using available model from your setup
default_model = "qwen2.5:7b-instruct"
temperature = 0.7
top_p = 0.9

# Optional: JSON output format for structured responses
# format = "json"

# Future TTS adapter example (commented out)
# [adapters.tts]
# provider = "fish-audio"
# version = "1.0.0"
#
# [adapters.tts.config]
# api_base = "https://api.fish.audio"
# voice_id = "default"
# speed = 1.0
