name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Check, Lint, Test and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Check Format
        run: cargo fmt --check

      - name: Run Linter
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Run Tests
        run: cargo test --all-targets --all-features

      - name: Build Release Binary
        run: cargo build --release
