name: Check

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  check:
    name: Check, Lint, and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Check Format
        run: cargo fmt --check

      - name: Run Linter
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Run Tests
        run: cargo test --all-targets --all-features
